Fix formatting errors (#2612)
**What this PR does / why we need it**:

Suspends these two errors:
```console
pkg/app/piped/planpreview/builder.go:231:13: Sprintf call has error-wrapping directive %w, which is only supported by Errorf

pkg/app/piped/sourcedecrypter/decrypter.go:36:10: Errorf format %w has arg enc.DecryptionTargets of wrong type []string
```

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:
<!--
If no, just write "NONE" in the release-note block below.
-->
```release-note
NONE
```

This PR was merged by Kapetanios.