Upgrade docsy to fix a bug related to offline search (#2621)
**What this PR does / why we need it**:

We are getting the following error related to offline search, so I upgraded docsy to the newest version to try to fix it.

```
hugo v0.88.1-5BC54738+extended linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "offline-search-index.json" (application/json): failed to parse Resource "offline-search-index.json" as Template:: template: offline-search-index.json:142: bad character U+005C '\'
Total in 10477 ms
```

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:
<!--
If no, just write "NONE" in the release-note block below.
-->
```release-note
NONE
```

This PR was merged by Kapetanios.