Fix flaky launcher test (#2758)
**What this PR does / why we need it**:

Suspend below flaky test
```console
(12:45:17) FAIL: //pkg/app/launcher/cmd/launcher:go_default_test (see /private/var/tmp/_bazel_/2d45f513ea3114123209fc663da944fe/execroot/pipe/bazel-out/darwin-fastbuild/testlogs/pkg/app/launcher/cmd/launcher/go_default_test/test.log)
(12:45:17) INFO: From Testing //pkg/app/launcher/cmd/launcher:go_default_test:
==================== Test output for //pkg/app/launcher/cmd/launcher:go_default_test:
--- FAIL: TestCommand (0.00s)
    binary_test.go:32: 
                Error Trace:    binary_test.go:32
                Error:          Should be false
                Test:           TestCommand
FAIL
================================================================================
```

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:
<!--
If no, just write "NONE" in the release-note block below.
-->
```release-note
NONE
```

This PR was merged by Kapetanios.